addSbtPlugin("au.com.onegeek"     %% "sbt-dotenv"              % "2.1.206")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"            % "2.4.0")
addSbtPlugin("org.wartremover"     % "sbt-wartremover"         % "2.4.11")
addSbtPlugin("org.wartremover"     % "sbt-wartremover-contrib" % "1.3.10")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"             % "0.2.0")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"            % "0.9.25")
